name: CMake build test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker://pachyderm/opencv:latest

    - name: Configure CMake
      run: |
        mkdir -p build && cd build
        cmake ..

    - name: Build
      run: |
        mkdir -p build && cd build
        cmake --build . --config {{env.BUILD_TYPE}}
