# name: CMake build test

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# env:
#   BUILD_TYPE: Release

# jobs:
#   build:
#     runs-on: pachyderm/opencv:latest

#     steps:
#     - uses: actions/checkout@v2

#     - name: Build
#       run: |
#         mkdir -p build && cd build
#         cmake ..
#         cmake --build . --config {{env.BUILD_TYPE}}
